export const REQUEST_LOGIN_START = 'REQUEST_LOGIN_START';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';
export const AUTO_LOGIN_SUCCESS = 'AUTO_LOGIN_SUCCESS';
export const AUTO_LOGIN_FAILED = 'AUTO_LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';

export const REQUEST_USER = 'REQUEST_USER';
export const USER_SAVE = 'USER_SAVE';
export const USER_IS_WORKING = 'USER_IS_WORKING';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_ERRORED = 'USER_ERRORED';
